'use client'
import { useState } from 'react'
import { Check, Loader2, Star } from 'lucide-react'
import { cn } from '@/lib/utils'
type Props = { source: 'complaint' | 'ai_assistant'; submissionKey: string; title: string; onDone?: () => void }
export function ReviewPrompt({ source, submissionKey, title, onDone }: Props) {
  const [rating,setRating]=useState(0), [comment,setComment]=useState(''), [submitting,setSubmitting]=useState(false), [done,setDone]=useState(false), [error,setError]=useState('')
  async function submit(){ if(!rating||submitting)return; setSubmitting(true);setError('');try{const response=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,comment,source,submissionKey})});const body=await response.json();if(!response.ok)throw new Error(body?.error||'Не удалось отправить отзыв.');setDone(true);onDone?.()}catch(err){setError((err as Error).message)}finally{setSubmitting(false)}}
  if(done)return <div className="rounded-xl border border-green-200 bg-green-50 p-5 text-sm text-green-800"><Check className="mr-2 inline h-4 w-4"/>Спасибо за отзыв!</div>
  return <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h3 className="text-base font-semibold">{title}</h3><div className="mt-3 flex gap-1" role="radiogroup">{[1,2,3,4,5].map(value=><button key={value} type="button" onClick={()=>setRating(value)} aria-label={`${value} из 5`} className="rounded p-1"><Star className={cn('h-8 w-8',value<=rating?'fill-amber-400 text-amber-400':'text-muted-foreground/30')}/></button>)}</div><label className="mt-4 block text-sm font-medium">{source==='complaint'?'Расскажите, что можно улучшить':'Что вы думаете о Jardem AI?'}<textarea value={comment} onChange={e=>setComment(e.target.value.slice(0,500))} maxLength={500} rows={3} placeholder="Напишите комментарий..." className="mt-2 w-full resize-y rounded-lg border border-input bg-background px-3 py-2 text-sm"/></label><div className="text-right text-xs text-muted-foreground">{comment.length}/500</div>{error&&<p className="mt-2 text-sm text-destructive">{error}</p>}<div className="mt-4 flex gap-2"><button type="button" onClick={submit} disabled={!rating||submitting} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{submitting&&<Loader2 className="h-4 w-4 animate-spin"/>}Отправить отзыв</button><button type="button" onClick={onDone} className="rounded-lg border px-4 py-2 text-sm">Пропустить</button></div></section>
}
